# Generated by Django 4.2.6 on 2023-11-01 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
