# Generated by Django 4.2.6 on 2023-11-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_platform', '0003_state_remove_address_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='status',
        ),
        migrations.RemoveField(
            model_name='state',
            name='status',
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=None, verbose_name='is active'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=None, verbose_name='is active'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='app_platform.state'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
